framework:
  rate_limiter:
    register_account:
      policy: 'token_bucket'
      limit: 5
      rate: { interval: '1 hour', amount: 1 }
    refresh_token:
      policy: 'token_bucket'
      limit: 10
      rate: { interval: '1 minute', amount: 10 }
